apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cma-proxy.fullname" . }}
data:
  proxy.conf: |-
{{- if eq .Values.mode "transparent" }}
    server {
        listen {{ .Values.service.port }} default_server;
        listen [::]:{{ .Values.service.port }} default_server;

        server_name _;

{{- if eq .Values.mode "kubeproxy" }}
{{- if .Values.basicAuth }}
        auth_basic           "Kubernetes API";
        auth_basic_user_file /etc/nginx/basicauth/.htpasswd;
{{- end }}
{{- end }}

        location / {
            proxy_pass $http_x_target_cluster;
        }
    }
{{- else }}  
    server {
        listen {{ .Values.service.port }} default_server;
        listen [::]:{{ .Values.service.port }} default_server;
        
        server_name _;

{{- if eq .Values.mode "kubeproxy" }}
{{- if .Values.basicAuth }}
        auth_basic           "Kubernetes API";
        auth_basic_user_file /etc/nginx/basicauth/.htpasswd;
{{- end }}
{{- end }}

{{- range $index, $cluster := .Values.clusters }}
        location /{{ $cluster.id }}/ {
{{- if eq $.Values.mode "kubeproxy" }}
            proxy_pass          http://127.0.0.1:{{ add $.Values.service.basePort $index }}/;
{{- else }}
            proxy_pass         {{ $cluster.endpoint | trimSuffix "/"}}/;
{{- end }}
            proxy_redirect     off;
        }
{{- end }}
    }
{{- end }}